---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-ui
  labels:
    app: etcd-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-ui
  template:
    metadata:
      labels:
        app: etcd-ui
    spec:
      containers:
      - name: ui
        image: quay.io/mengzn/etcdkeeper
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-ui
spec:
  selector:
    app: etcd-ui
  ports:
  - protocol: TCP
    nodePort: 32767
    port: 80
    targetPort: 8080
  type: NodePort
